name: CI

on: [push]

jobs:
  run-the-script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Preparation steps
      run: |
        ls -lah
        chmod 700 test_cred_alert.sh
        chmod 700 credentials_alert.sh
    - name: Running the tests
      run: |
        ./test_cred_alert.sh
