name: CI

on: [push]

jobs:
  run-the-script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        echo "Running the test script"
        ls -lah
        chmod 700 test_cred_alert.sh
        ./test_cred_alert.sh
        echo "Finish"
